
services:
  backend:
    build:
      context: ./backend
    container_name: linkifybackendproj
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - linkify-net

  frontend:
    build:
      context:  "./LinkedIn Clone"
      args:
        VITE_BACKEND_URL: "http://localhost:3000"
    container_name: linkifyfrontendproj
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - linkify-net

networks:
  linkify-net:
    driver: bridge
